### ISSUE TITLE
build fails with node 0.8

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/livestyle#43]
After the mocha rewrite of the test suite there's some flaking on a test case on CI, only seen on the node 0.8 build so far.

https://travis-ci.org/One-com/livestyle/jobs/27723710

livestyle server in non-proxy mode should notify subscribers about changes in css

I saw it when pushing to my pull request - and I fixed it, I believed. I could reproduce it locally with 0.8, and found a fix for it (using async file writes and waiting for the callback instead of using sync writes) that allowed me to avoid the timeouts which were present earlier.

I'll have to look into this again, as the same error apparently just popped up now.

**Comment by Munter** [comment]
By now I would say node 0.8 is outdated. Should we just close this as irrelevant?

**Comment by gustavnikolaj** [comment]
Fine with me :-) Let's make a new major version and stop supporting 0.8.

**Comment by gustavnikolaj** [comment]
@Munter I see that you already removed the 0.8 from travis. https://github.com/One-com/livestyle/commit/8e87a77373f38cff3e30f9d927c9911c9ed1c729

I think we should update the engines field in [package.json](https://github.com/One-com/livestyle/blob/d1e74d3273fae3a80c3e33480ee2943f7cf079aa/package.json#L24) and tag a new major verison, and then close this issue :-)

**Comment by Munter** [comment]
v2.0.0 is out
