### ISSUE TITLE
Build fails on node.js 0.12 and io.js 2.5.0

### ISSUE THREAD

**Issue by papandreou** [One-com/livestyle#54]
After [I added node.js 0.12 and io.js to .travis.yml](https://github.com/One-com/livestyle/commit/d840d184a49206b85a729bb340a0569f916986dd), the build started failing on those platforms: https://travis-ci.org/One-com/livestyle/jobs/73107760

So the failing build is probably not a regression, but at least we know that it doesn't work there now :)

**Comment by Munter** [comment]
node-sass in a really ancient version. I'll take a look at it
